//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_Compas_App.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjectMasterEntities : DbContext
    {
        public ProjectMasterEntities()
            : base("name=ProjectMasterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<MenuMaster> MenuMasters { get; set; }
        public DbSet<RoleMappMaster> RoleMappMasters { get; set; }
        public DbSet<RoleMaster> RoleMasters { get; set; }
        public DbSet<User_Login> User_Login { get; set; }
        public DbSet<UserMaster> UserMasters { get; set; }
    }
}
