//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_Compas_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleMaster
    {
        public RoleMaster()
        {
            this.UserMasters = new HashSet<UserMaster>();
        }
    
        public int RoleId { get; set; }
        public string RoleName { get; set; }
        public string RoleDesc { get; set; }
        public string RoleStatus { get; set; }
    
        public virtual ICollection<UserMaster> UserMasters { get; set; }
    }
}
