//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_Compas_App.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class RoleMaster
    {
        public int RoleId { get; set; }
        [Required]
        [DisplayName("Role Name")]
        public string RoleName { get; set; }
        [DisplayName("Role Discripation")]
        public string RoleDesc { get; set; }
        [DisplayName("Role Status")]
        public string RoleStatus { get; set; }
    }
}
