//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_Compas_App.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class TomatoProductInfo
    {

        public int Product_Id { get; set; }
        [DisplayName ("Product Name")]
        [Required]
        public string Pname { get; set; }
        [DisplayName("Product Quntity")]
        public string Pquntity { get; set; }
        [DisplayName("Product Type")]
        public string Ptypes { get; set; }
        [DisplayName("Product City")]
        public string Pcity { get; set; }
        [DisplayName("Date of issue")]
        [Required]
        public Nullable<System.DateTime> Pdate { get; set; }
    }
}
