//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_Compas_App.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class UserMaster
    {
        public int UserId { get; set; }
        public string UserFname { get; set; }
        public string UserLname { get; set; }
        public string UserName { get; set; }
        public string UserPassword { get; set; }
        public string UserEmail { get; set; }
        public Nullable<int> UserContactno { get; set; }
        [DisplayName("Role Name")]
        public Nullable<int> RoleId { get; set; }
        public Nullable<bool> isActive { get; set; }
    
        public virtual RoleMaster RoleMaster { get; set; }
        [NotMapped]
        public List<RoleMaster> RoleCollection { get; set; }
    }
}
